namespace RemnaBotService
{
    public class DialogContainer
    {
        public static string[] BlockStory = new string[]
        {
        "You raise your shield just in time, deflecting the Dragon's fiery breath!",
        "With a swift move, you parry the Dragon's attack, minimizing the damage!",
        "You brace yourself against the Dragon's onslaught, absorbing the blow!",
        "Your shield holds strong, protecting you from the Dragon's claws!",
        "You deflect the Dragon's attack with a well-timed block!",
        "The Dragon's attack crashes against your defenses, but you stand firm!",
        "You anticipate the Dragon's move and block with precision!",
        "You take the hit, but your defenses mitigate the impact!",
        "The Dragon's attack leaves you shaken, but your shield holds!",
        "You grit your teeth and withstand the Dragon's fury!",
        "With a grunt, you brace yourself and block the Dragon's attack!",
        "The Dragon's attack sends tremors through your body, but you hold your ground!",
        "You absorb the Dragon's attack, protecting yourself from the worst!",
        "Your shield deflects the Dragon's attack, sending sparks flying!",
        "You block the Dragon's attack with a resounding clang!",
        "The Dragon's claws scrape against your shield, but you remain unscathed!",
        "You deflect the Dragon's fiery breath, sending it spiraling into the sky!",
        "With a well-placed block, you redirect the Dragon's attack!",
        "You stand your ground, shielding yourself from the Dragon's wrath!",
        "The Dragon's attack tests your resolve, but you do not yield!",
        "You feel the force of the Dragon's attack, but your block holds!",
        "The Dragon's attack leaves you winded, but your shield protects you!",
        "With a mighty roar, you block the Dragon's attack, showcasing your strength!",
        "You are a bulwark against the Dragon's fury, your block unwavering!",
        "The Dragon's attack is fierce, but your block is stronger!",
        "You have faced the Dragon's wrath and survived, your shield a testament to your courage!",
        "The Dragon's attack is a reminder of the danger you face, but you will not falter!",
        "You block the Dragon's attack, a symbol of your defiance against its power!",
        "The Dragon's attack is a challenge, but you meet it with unwavering resolve!",
        "You are the shield against the Dragon's fury, protecting yourself and those you defend!",
        "The Dragon's attack is a test of your strength, and you have proven yourself worthy!",
        "You have stared into the face of the Dragon's wrath and emerged victorious, your shield a symbol of your triumph!",
        "The Dragon's claws leave deep gouges in your shield, a reminder of the battle's intensity!",
        "You feel the heat of the Dragon's breath as it washes over your shield, but you stand firm!",
        "With a mighty heave, you deflect the Dragon's attack, sending it crashing into the rocks!",
        "The Dragon's attack is a tempest, but you are the unmovable mountain!",
        "You are the shield that protects against the Dragon's fury, your block a beacon of hope!",
        "The Dragon's attack is a challenge, and you meet it with unwavering determination!",
        "You have faced the Dragon's wrath and emerged stronger, your shield a symbol of your resilience!",
        "The Dragon's claws leave scratches on your shield, a testament to the battle's ferocity!",
        "You feel the heat of the Dragon's breath as it scorches your shield, but you hold your ground!",
        "With a mighty roar, you deflect the Dragon's attack, sending it spiraling into the abyss!",
        "The Dragon's attack is a storm, but you are the unyielding fortress!",
        "You are the shield against the Dragon's fury, your block a symbol of courage and strength!",
        "The Dragon's attack is a trial, and you have proven yourself worthy!",
        "You have stared into the face of the Dragon's wrath and emerged victorious, your shield a symbol of your unwavering spirit!"

        };

        public static string[] BraveSuccessStory = new string[]
    {
        "With a mighty roar, you unleash your fury upon the Dragon!",
        "Your blade finds its mark, piercing the Dragon's defenses!",
        "You strike with precision, leaving the Dragon reeling in pain!",
        "A surge of adrenaline fuels your attack, overwhelming the Dragon!",
        "Your courage pays off as you land a solid blow!",
        "You channel your inner strength, delivering a thunderous strike!",
        "With a swift and decisive move, you cut through the Dragon's scales!",
        "The Dragon falters under the force of your relentless assault!",
        "You seize the moment and unleash a flurry of attacks!",
        "Your attack resonates with power, shaking the very ground beneath you!",
        "You dance around the Dragon's clumsy attacks and land a critical hit!",
        "The Dragon roars in pain as your attack tears through its flesh!",
        "You exploit a weakness in the Dragon's armor, dealing significant damage!",
        "Your attack echoes through the cavern, a testament to your bravery!",
        "The Dragon is caught off guard by your audacious move!",
        "You unleash a primal scream as you charge towards the Dragon!",
        "With a battle cry, you leap forward and strike with all your might!",
        "The Dragon staggers back, surprised by the ferocity of your attack!",
        "You feel the power coursing through your veins as you strike!",
        "Your attack leaves a trail of fire in its wake!",
        "You strike with the speed of lightning, leaving the Dragon little chance to react!",
        "The Dragon is struggling against your unwavering resolve!",
        "You fight with the heart of a lion, and your attack reflects that!",
        "The Dragon's eyes narrow as your blade descends!",
        "You have drawn blood, and the Dragon's rage intensifies!",
        "Your attack is a masterpiece of skill and precision!",
        "The Dragon's scales offer limited protection against your mighty blow!",
        "You strike with the force of a thunderbolt, leaving the Dragon momentarily stunned!",
        "Your attack is a whirlwind of steel, pushing back the Dragon's defenses!",
        "You have struck a significant blow, and the Dragon's strength begins to wane!",
        "With a cunning feint, you create an opening and strike with deadly accuracy!",
        "The Dragon's roar turns into a snarl as your attack lands true!",
        "You have struck a vital blow, and the Dragon's power is diminished!",
        "Your attack is a symphony of destruction, leaving the Dragon battered and bruised!",
        "You have proven your mettle, and the Dragon's respect (or fear) grows!",
        "With a powerful strike, you press your advantage!",
        "You have wounded the Dragon, but the battle is far from over!",
        "Your attack has weakened the Dragon, but it still fights with ferocity!",
        "You have tasted the Dragon's blood, and the scent of victory is in the air!",
        "Your attack has broken the Dragon's concentration, giving you a chance to strike again!",
        "The Dragon's eyes gleam with a mix of pain and fury!",
        "You have made the Dragon bleed, and it knows that you are a worthy opponent!",
        "Your attack has shaken the Dragon's confidence, and it begins to doubt its own strength!",
        "You have shown the Dragon that you are not afraid to challenge it!",
        "The Dragon's scales are scarred, and its pride is wounded!",
        "You have pushed the Dragon to its limits, and it is beginning to tire!",
        "Your attack has ignited a fire within you, and you are ready to finish the fight!",
        "The Dragon's roar is a challenge, and you are eager to answer it!",
        "You have drawn the Dragon's attention, and it knows that you are a threat!",
        "Your attack has earned you the Dragon's respect (or fear), and the battle rages on!",
        "The Dragon's scales are chipped, and its spirit is tested!",
        "You have proven yourself a formidable opponent, and the Dragon knows that it is in for a long fight!",
        "Your attack has given you the upper hand, but the Dragon is not yet defeated!",
        "The Dragon's eyes burn with a renewed determination, and the battle intensifies!",
        "You have drawn the Dragon's ire, and it will stop at nothing to defeat you!",
        "Your attack has made the Dragon realize that it is not invincible!",
        "The Dragon's scales are scarred, and its heart is filled with a mixture of rage and respect!",
        "You have shown the Dragon that you are a force to be reckoned with, and the battle continues!",
        "The Dragon's roar is a challenge, and you are eager to meet it head-on!",
        "Your attack has made the Dragon realize that it is in a fight for its life!",
        "The Dragon's scales are chipped, and its spirit is tested, but it will not yield!",
        "You have proven yourself a worthy adversary, and the Dragon knows that it must fight with all its might to prevail!",
        "Your attack has given you a glimmer of hope, but the Dragon is still a formidable foe!",
        "The Dragon's eyes burn with a renewed determination, and the battle rages on with renewed intensity!"
    };

        public static string[] BraveFailureStory = new string[]
   {
        "Your attack falters, and the Dragon seizes the opportunity!",
        "The Dragon anticipates your move and counters with a swift strike!",
        "Your blade glances harmlessly off the Dragon's thick scales!",
        "You stumble, leaving yourself open to the Dragon's attack!",
        "The Dragon's roar echoes as it unleashes its fury upon you!",
        "Your courage falters at the crucial moment!",
        "The Dragon's defenses prove too strong for your attack!",
        "You hesitate, giving the Dragon the advantage!",
        "Your attack lacks the power to penetrate the Dragon's armor!",
        "The Dragon laughs as your attack falls short!",
        "You are overwhelmed by the Dragon's might!",
        "Your attack is clumsy and ineffective!",
        "The Dragon's scales deflect your blade with ease!",
        "You misjudge the distance and miss your target!",
        "The Dragon sidesteps your attack with a mocking grin!",
        "Your attack is a desperate gamble that fails!",
        "You are no match for the Dragon's superior strength!",
        "Your attack is a mere annoyance to the mighty Dragon!",
        "The Dragon's eyes gleam with malice as it prepares to strike!",
        "You have underestimated the Dragon's power!",
        "Your attack is a futile attempt to challenge the Dragon's dominance!",
        "The Dragon's roar fills you with dread as it prepares to retaliate!",
        "You have made a grave mistake in challenging the Dragon!",
        "Your bravery has turned to recklessness, and you are punished!",
        "The Dragon's claws rake across your armor, leaving deep gashes!",
        "You feel the Dragon's fiery breath scorching your skin!",
        "The Dragon's tail whips around and knocks you off your feet!",
        "You are caught in the Dragon's whirlwind of fury!",
        "The Dragon's teeth sink into your flesh, and you cry out in pain!",
        "You are at the Dragon's mercy, and it shows you none!",
        "The Dragon's attack leaves you battered and bruised!",
        "You have faltered before the might of the Dragon, but the fight is not over!",
        "Your spirit is tested, and your will to fight is strained!",
        "The Dragon's power is immense, and your resilience is tested!",
        "You have been wounded by the Dragon's fury, but you must persevere!",
        "The Dragon's laughter echoes through the cavern, a reminder of your vulnerability!",
        "You have challenged the Dragon and suffered a setback, but the battle continues!",
        "The Dragon's power is formidable, and your resolve is tested!",
        "You have been singed by the Dragon's flames, but you are not yet broken!",
        "The Dragon's attack is a reminder of its power, and you must be cautious!",
        "You have been humbled by the Dragon's might, but you will not yield!",
        "The Dragon's claws leave marks on your armor, a reminder of the danger you face!",
        "You feel the heat of the Dragon's breath as it washes over you, but you stand firm!",
        "With a snarl, the Dragon prepares to unleash another attack!",
        "The Dragon's power is undeniable, and your determination is tested!",
        "You have been wounded, but you are not defeated!",
        "The Dragon's eyes gleam with a predatory hunger!",
        "You have challenged the Dragon, and it has responded with overwhelming force!",
        "The Dragon's scales are a formidable defense, and your attacks have barely scratched the surface!",
   };

        public static string[] VictoryStory = new string[]
{
        "With a final, desperate lunge, you deliver the coup de grâce!",
        "The Dragon's reign of terror is over, and your name will be sung in legends!",
        "You stand victorious over the fallen Dragon, your blade dripping with its lifeblood!",
        "Your bravery and skill have prevailed, and the kingdom is safe once more!",
        "The Dragon's treasure is yours for the taking, a reward for your valor!",
        "You have earned your place among the heroes of old, your name forever etched in history!",
        "The Dragon's defeat is a testament to your unwavering spirit and indomitable will!",
        "You have conquered the beast, and in doing so, you have conquered your own fears!",
        "The Dragon's fall is a symbol of hope for all those who dare to dream!",
        "You have shown the world that even the mightiest of dragons can be defeated with courage and skill!",
        "The Dragon's demise is a victory for all those who have ever faced adversity and refused to give up!",
        "You have emerged from the battle stronger and more determined than ever before!",
        "The Dragon's defeat is a reminder that even in the darkest of times, hope can prevail!",
        "You have proven yourself a true hero, and your name will forever be associated with courage, strength, and victory!",
        "The Dragon's fall is a symbol of the triumph of good over evil, and your name will forever be associated with that triumph!",
        "You have vanquished the beast that terrorized the land!",
        "The Dragon's fire is extinguished, and a new dawn breaks!",
        "Your name will be spoken with reverence for generations to come!",
        "The kingdom rejoices at the news of the Dragon's defeat!",
        "You are the champion, the hero who saved the realm!",
        "The Dragon's hoard is now yours to command!",
        "Your legend will live on, inspiring others to greatness!",
        "The world is a safer place because of your bravery!",
        "You have proven yourself worthy of the title of hero!",
        "The Dragon's defeat is a victory for all that is good and just!",
        "You are the light that pierced the darkness, the hope that banished despair!",
        "The Dragon's fall is a testament to the power of courage and the strength of the human spirit!",
        "You have faced the ultimate challenge and emerged victorious, a true hero among heroes!",
        "The Dragon's defeat is a symbol of the triumph of hope over fear, and your name will forever be associated with that triumph!",
        "You have conquered the beast that threatened to consume the world, and your victory will be celebrated for centuries to come!",
        "The Dragon's fire is no more, its roar silenced forever, and your name will be remembered as the one who brought peace back to the land!",
        "You have shown the world that even the most fearsome of foes can be defeated with courage, skill, and an unwavering belief in oneself!",
        "The Dragon's defeat is a victory for all those who have ever dared to dream of a better world, a world free from fear and oppression!",
        "You have earned your place among the legendary heroes of old, your name forever etched in the annals of history as the Dragon Slayer!"

};

        public static string[] DefeatStory = new string[]
  {
        "The Dragon's attack is a final, devastating blow that extinguishes your life!",
        "Your story ends here, a tale of courage and defeat, a reminder of the Dragon's might!",
        "The Dragon's roar is a dirge for your fallen soul, and its victory is complete!",
        "You have faced the Dragon and met your doom, a victim of its overwhelming power!",
        "The Dragon's reign of terror continues, and your name will be added to its list of victims!",
        "Your sacrifice was in vain, and the kingdom mourns the loss of its hero!",
        "The Dragon's victory is a tragedy, and your memory will forever be a reminder of the cost of failure!",
        "You have fought your last battle, and the Dragon stands triumphant over your lifeless body!",
        "The Dragon's power is absolute, and your defeat is a testament to its might!",
        "You have fallen, and the world is plunged into darkness, for the Dragon's reign of terror has begun!",
        "Your name will be whispered in fear, a reminder of the Dragon's power and your own demise!",
        "The Dragon's victory is complete, and your story ends here, a tale of courage and defeat, a testament to the might of the Dragon!",
        "Your light has been extinguished, and the darkness has prevailed.",
        "The Dragon's flames have consumed you, leaving only ashes.",
        "Your valiant effort was not enough, and the Dragon's power has overwhelmed you.",
        "The world has lost a hero, and the Dragon's victory is a crushing blow to hope.",
        "Your name will be remembered, but not as the victor, but as the one who dared to challenge the Dragon and fell.",
        "The Dragon's legend grows with each fallen hero, and yours is now a part of its tale.",
        "Your journey ends here, a testament to the Dragon's might and the fragility of human courage.",
        "The Dragon's victory is a somber reminder of the power of darkness and the cost of defiance.",
        "You have fought bravely, but in the end, the Dragon's power was too great to overcome.",
        "Your spirit is broken, your body defeated, and the Dragon's victory is complete.",
        "The world mourns the loss of a hero, and the Dragon's shadow looms large over the land.",
        "Your name will be etched in the annals of history, not as a champion, but as a symbol of the Dragon's power.",
        "The Dragon's victory is a tragedy, a reminder of the cost of courage and the might of the beast.",
        "You have fallen, but your memory will live on, a reminder of the courage it takes to face the darkness.",
        "The Dragon's reign of terror continues, and your defeat serves as a warning to all who dare to challenge its power.",
        "Your sacrifice was valiant, but in the end, it was not enough to defeat the Dragon.",
        "The world is a darker place without your light, and the Dragon's victory is a symbol of the triumph of evil.",
        "You have fought with honor, but in the end, the Dragon's power was too great to overcome, and your story ends here.",
        "Your name will be spoken with a mix of awe and sorrow, a reminder of your courage and the Dragon's might.",
        "The Dragon's victory is a tragedy, but your memory will inspire others to fight against the darkness, even in the face of overwhelming odds.",
        "You have fallen, but your spirit will live on, a beacon of hope in a world shrouded in shadow."
  };

        public static string[] ClashStory = new string[]
   {
        "You and the Dragon clash, neither able to gain an advantage!",
        "Steel meets scale in a resounding clang, as both combatants stand their ground!",
        "A fierce exchange of blows results in a stalemate, neither side yielding!",
        "The Dragon's fury is matched by your unwavering resolve, resulting in a clash of titans!",
        "Sparks fly as your weapons meet, neither attack able to break through the other's defenses!",
        "You and the Dragon lock in a struggle of wills, neither giving an inch!",
        "The ground trembles as your combined power reverberates through the cavern!",
        "Neither you nor the Dragon can land a decisive blow, the battle hanging in the balance!",
        "The clash of your weapons echoes through the air, a testament to the ferocity of the fight!",
        "You and the Dragon are locked in a deadly dance, each mirroring the other's moves!",
        "The Dragon's might is met with your equal strength, resulting in a thunderous collision!",
        "Neither side can gain the upper hand, the battle a true test of endurance!",
        "You and the Dragon are evenly matched, the outcome of the battle still uncertain!",
        "The clash of your attacks creates a shockwave, pushing both combatants back!",
        "Neither you nor the Dragon can break through the other's defenses, the battle at a standstill!",
        "The Dragon's roar is answered by your battle cry, as the clash intensifies!",
        "You and the Dragon are locked in a struggle for dominance, neither willing to yield!",
        "The clash of your weapons is a symphony of destruction, as the battle reaches its climax!",
        "Neither side can deliver the final blow, the battle hanging by a thread!",
        "You and the Dragon are engaged in a battle of attrition, each waiting for the other to falter!",
        "The Dragon's power is matched by your determination, the clash a testament to your resilience!",
        "Neither combatant can gain a clear advantage, the battle a true test of skill and strength!",
        "You and the Dragon are locked in a deadly embrace, neither able to break free!",
        "The clash of your attacks is a whirlwind of fury, as the battle reaches its peak!",
        "Neither side can land a telling blow, the battle a stalemate of epic proportions!",
        "The Dragon's might is countered by your unwavering spirit, the clash a symbol of your defiance!",
        "You and the Dragon are engaged in a battle of wills, neither prepared to back down!",
        "The clash of your weapons is a deafening roar, as the battle reaches its crescendo!",
        "Neither combatant can deliver the coup de grâce, the battle hanging in the balance!",
        "You and the Dragon are locked in a struggle for survival, neither willing to surrender!",
        "The Dragon's power is matched by your unwavering courage, the clash a testament to your bravery!",
        "Neither side can gain a decisive edge, the battle a true test of heart and determination!",
        "You and the Dragon are locked in a dance of death, neither able to escape!",
        "The clash of your attacks is a symphony of chaos, as the battle reaches its most intense point!",
        "Neither combatant can land the final blow, the battle a stalemate of legendary proportions!",
        "The Dragon's might is countered by your unwavering resolve, the clash a symbol of your indomitable spirit!",
        "You and the Dragon are locked in a struggle for victory, neither willing to concede defeat!",
        "The clash of your weapons is a thunderous explosion, as the battle reaches its most critical juncture!",
        "Neither side can deliver the killing stroke, the battle hanging by a thread!",
        "You and the Dragon are engaged in a battle for supremacy, neither willing to relinquish control!",
        "The Dragon's power is matched by your unwavering tenacity, the clash a testament to your unwavering will!",
        "Neither combatant can gain a clear advantage, the battle a true test of grit and determination!",
        "You and the Dragon are locked in a deadly confrontation, neither able to break the deadlock!",
        "The clash of your attacks is a maelstrom of destruction, as the battle reaches its most crucial moment!",
        "Neither side can land the decisive blow, the battle a stalemate of epic proportions!",
        "The Dragon's might is countered by your unwavering valor, the clash a symbol of your unyielding spirit!",
        "You and the Dragon are engaged in a battle for dominance, neither prepared to yield!",
        "The clash of your weapons is a cataclysmic event, as the battle reaches its most decisive point!"

   };


    }
}